// Code generated by Wire protocol buffer compiler, do not edit.
// Source: test3.TestService3 in test3.proto
package com.proto.test3

import com.squareup.wire.GrpcCall
import com.squareup.wire.Service

public interface TestService3Client : Service {
  /**
   * Unary
   */
  public fun test(): GrpcCall<TestService3Request, TestService3Response>
}
