// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dino.proto

package com.proto.dino;

/**
 * Protobuf type {@code test3.Dinosaur}
 */
public final class Dinosaur extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:test3.Dinosaur)
    DinosaurOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Dinosaur.newBuilder() to construct.
  private Dinosaur(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Dinosaur() {
    name_ = "";
    pictureUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    period_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Dinosaur();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.proto.dino.Dino.internal_static_test3_Dinosaur_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.proto.dino.Dino.internal_static_test3_Dinosaur_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.proto.dino.Dinosaur.class, com.proto.dino.Dinosaur.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * Common name of this dinosaur, like "Stegosaurus".
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Common name of this dinosaur, like "Stegosaurus".
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PICTURE_URLS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList pictureUrls_;
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @return A list containing the pictureUrls.
   */
  public com.google.protobuf.ProtocolStringList
      getPictureUrlsList() {
    return pictureUrls_;
  }
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @return The count of pictureUrls.
   */
  public int getPictureUrlsCount() {
    return pictureUrls_.size();
  }
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @param index The index of the element to return.
   * @return The pictureUrls at the given index.
   */
  public java.lang.String getPictureUrls(int index) {
    return pictureUrls_.get(index);
  }
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the pictureUrls at the given index.
   */
  public com.google.protobuf.ByteString
      getPictureUrlsBytes(int index) {
    return pictureUrls_.getByteString(index);
  }

  public static final int PERIOD_FIELD_NUMBER = 5;
  private int period_;
  /**
   * <code>.test3.Period period = 5;</code>
   * @return The enum numeric value on the wire for period.
   */
  @java.lang.Override public int getPeriodValue() {
    return period_;
  }
  /**
   * <code>.test3.Period period = 5;</code>
   * @return The period.
   */
  @java.lang.Override public com.proto.dino.Period getPeriod() {
    @SuppressWarnings("deprecation")
    com.proto.dino.Period result = com.proto.dino.Period.valueOf(period_);
    return result == null ? com.proto.dino.Period.UNRECOGNIZED : result;
  }

  public static com.proto.dino.Dinosaur parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.dino.Dinosaur parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.dino.Dinosaur parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.dino.Dinosaur parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.dino.Dinosaur parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.dino.Dinosaur parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.dino.Dinosaur parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.dino.Dinosaur parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.dino.Dinosaur parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.proto.dino.Dinosaur parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.dino.Dinosaur parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.dino.Dinosaur parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.proto.dino.Dinosaur prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code test3.Dinosaur}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:test3.Dinosaur)
      com.proto.dino.DinosaurOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.dino.Dino.internal_static_test3_Dinosaur_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.dino.Dino.internal_static_test3_Dinosaur_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.dino.Dinosaur.class, com.proto.dino.Dinosaur.Builder.class);
    }

    // Construct using com.proto.dino.Dinosaur.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      pictureUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      period_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.proto.dino.Dino.internal_static_test3_Dinosaur_descriptor;
    }

    @java.lang.Override
    public com.proto.dino.Dinosaur getDefaultInstanceForType() {
      return com.proto.dino.Dinosaur.getDefaultInstance();
    }

    @java.lang.Override
    public com.proto.dino.Dinosaur build() {
      com.proto.dino.Dinosaur result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.proto.dino.Dinosaur buildPartial() {
      com.proto.dino.Dinosaur result = new com.proto.dino.Dinosaur(this);
      int from_bitField0_ = bitField0_;
      result.name_ = name_;
      if (((bitField0_ & 0x00000001) != 0)) {
        pictureUrls_ = pictureUrls_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.pictureUrls_ = pictureUrls_;
      result.period_ = period_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Common name of this dinosaur, like "Stegosaurus".
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Common name of this dinosaur, like "Stegosaurus".
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Common name of this dinosaur, like "Stegosaurus".
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Common name of this dinosaur, like "Stegosaurus".
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Common name of this dinosaur, like "Stegosaurus".
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList pictureUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensurePictureUrlsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        pictureUrls_ = new com.google.protobuf.LazyStringArrayList(pictureUrls_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @return A list containing the pictureUrls.
     */
    public com.google.protobuf.ProtocolStringList
        getPictureUrlsList() {
      return pictureUrls_.getUnmodifiableView();
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @return The count of pictureUrls.
     */
    public int getPictureUrlsCount() {
      return pictureUrls_.size();
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @param index The index of the element to return.
     * @return The pictureUrls at the given index.
     */
    public java.lang.String getPictureUrls(int index) {
      return pictureUrls_.get(index);
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the pictureUrls at the given index.
     */
    public com.google.protobuf.ByteString
        getPictureUrlsBytes(int index) {
      return pictureUrls_.getByteString(index);
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @param index The index to set the value at.
     * @param value The pictureUrls to set.
     * @return This builder for chaining.
     */
    public Builder setPictureUrls(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePictureUrlsIsMutable();
      pictureUrls_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @param value The pictureUrls to add.
     * @return This builder for chaining.
     */
    public Builder addPictureUrls(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePictureUrlsIsMutable();
      pictureUrls_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @param values The pictureUrls to add.
     * @return This builder for chaining.
     */
    public Builder addAllPictureUrls(
        java.lang.Iterable<java.lang.String> values) {
      ensurePictureUrlsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, pictureUrls_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPictureUrls() {
      pictureUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @param value The bytes of the pictureUrls to add.
     * @return This builder for chaining.
     */
    public Builder addPictureUrlsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensurePictureUrlsIsMutable();
      pictureUrls_.add(value);
      onChanged();
      return this;
    }

    private int period_ = 0;
    /**
     * <code>.test3.Period period = 5;</code>
     * @return The enum numeric value on the wire for period.
     */
    @java.lang.Override public int getPeriodValue() {
      return period_;
    }
    /**
     * <code>.test3.Period period = 5;</code>
     * @param value The enum numeric value on the wire for period to set.
     * @return This builder for chaining.
     */
    public Builder setPeriodValue(int value) {
      
      period_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.test3.Period period = 5;</code>
     * @return The period.
     */
    @java.lang.Override
    public com.proto.dino.Period getPeriod() {
      @SuppressWarnings("deprecation")
      com.proto.dino.Period result = com.proto.dino.Period.valueOf(period_);
      return result == null ? com.proto.dino.Period.UNRECOGNIZED : result;
    }
    /**
     * <code>.test3.Period period = 5;</code>
     * @param value The period to set.
     * @return This builder for chaining.
     */
    public Builder setPeriod(com.proto.dino.Period value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      period_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.test3.Period period = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPeriod() {
      
      period_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:test3.Dinosaur)
  }

  // @@protoc_insertion_point(class_scope:test3.Dinosaur)
  private static final com.proto.dino.Dinosaur DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.proto.dino.Dinosaur();
  }

  public static com.proto.dino.Dinosaur getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Dinosaur>
      PARSER = new com.google.protobuf.AbstractParser<Dinosaur>() {
    @java.lang.Override
    public Dinosaur parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(
                builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Dinosaur> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Dinosaur> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.proto.dino.Dinosaur getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

