// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dino.proto

package com.proto.dino;

public interface DinosaurOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test3.Dinosaur)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Common name of this dinosaur, like "Stegosaurus".
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Common name of this dinosaur, like "Stegosaurus".
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @return A list containing the pictureUrls.
   */
  java.util.List<java.lang.String>
      getPictureUrlsList();
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @return The count of pictureUrls.
   */
  int getPictureUrlsCount();
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @param index The index of the element to return.
   * @return The pictureUrls at the given index.
   */
  java.lang.String getPictureUrls(int index);
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @param index The index of the element to return.
   * @return The pictureUrls at the given index.
   */
  com.google.protobuf.ByteString
      getPictureUrlsBytes(int index);

  /**
   * <code>.test3.Period period = 5;</code>
   * @return The enum numeric value on the wire for period.
   */
  int getPeriodValue();
  /**
   * <code>.test3.Period period = 5;</code>
   * @return The period.
   */
  com.proto.dino.Period getPeriod();
}
