// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dino.proto

package com.proto.dino;

/**
 * Protobuf type {@code test3.Dinosaur}
 */
public  final class Dinosaur extends
    com.google.protobuf.GeneratedMessageLite<
        Dinosaur, Dinosaur.Builder> implements
    // @@protoc_insertion_point(message_implements:test3.Dinosaur)
    DinosaurOrBuilder {
  private Dinosaur() {
    name_ = "";
    pictureUrls_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <pre>
   * Common name of this dinosaur, like "Stegosaurus".
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <pre>
   * Common name of this dinosaur, like "Stegosaurus".
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <pre>
   * Common name of this dinosaur, like "Stegosaurus".
   * </pre>
   *
   * <code>string name = 1;</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    name_ = value;
  }
  /**
   * <pre>
   * Common name of this dinosaur, like "Stegosaurus".
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <pre>
   * Common name of this dinosaur, like "Stegosaurus".
   * </pre>
   *
   * <code>string name = 1;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();
    
  }

  public static final int PICTURE_URLS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> pictureUrls_;
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @return A list containing the pictureUrls.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getPictureUrlsList() {
    return pictureUrls_;
  }
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @return The count of pictureUrls.
   */
  @java.lang.Override
  public int getPictureUrlsCount() {
    return pictureUrls_.size();
  }
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @param index The index of the element to return.
   * @return The pictureUrls at the given index.
   */
  @java.lang.Override
  public java.lang.String getPictureUrls(int index) {
    return pictureUrls_.get(index);
  }
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the pictureUrls at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPictureUrlsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        pictureUrls_.get(index));
  }
  private void ensurePictureUrlsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        pictureUrls_;  if (!tmp.isModifiable()) {
      pictureUrls_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @param index The index to set the value at.
   * @param value The pictureUrls to set.
   */
  private void setPictureUrls(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensurePictureUrlsIsMutable();
    pictureUrls_.set(index, value);
  }
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @param value The pictureUrls to add.
   */
  private void addPictureUrls(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensurePictureUrlsIsMutable();
    pictureUrls_.add(value);
  }
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @param values The pictureUrls to add.
   */
  private void addAllPictureUrls(
      java.lang.Iterable<java.lang.String> values) {
    ensurePictureUrlsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, pictureUrls_);
  }
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   */
  private void clearPictureUrls() {
    pictureUrls_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   * URLs with images of this dinosaur.
   * </pre>
   *
   * <code>repeated string picture_urls = 2;</code>
   * @param value The bytes of the pictureUrls to add.
   */
  private void addPictureUrlsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensurePictureUrlsIsMutable();
    pictureUrls_.add(value.toStringUtf8());
  }

  public static final int PERIOD_FIELD_NUMBER = 5;
  private int period_;
  /**
   * <code>.test3.Period period = 5;</code>
   * @return The enum numeric value on the wire for period.
   */
  @java.lang.Override
  public int getPeriodValue() {
    return period_;
  }
  /**
   * <code>.test3.Period period = 5;</code>
   * @return The period.
   */
  @java.lang.Override
  public com.proto.dino.Period getPeriod() {
    com.proto.dino.Period result = com.proto.dino.Period.forNumber(period_);
    return result == null ? com.proto.dino.Period.UNRECOGNIZED : result;
  }
  /**
   * <code>.test3.Period period = 5;</code>
   * @param value The enum numeric value on the wire for period to set.
   */
  private void setPeriodValue(int value) {
      period_ = value;
  }
  /**
   * <code>.test3.Period period = 5;</code>
   * @param value The period to set.
   */
  private void setPeriod(com.proto.dino.Period value) {
    period_ = value.getNumber();
    
  }
  /**
   * <code>.test3.Period period = 5;</code>
   */
  private void clearPeriod() {
    
    period_ = 0;
  }

  public static com.proto.dino.Dinosaur parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.proto.dino.Dinosaur parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.proto.dino.Dinosaur parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.proto.dino.Dinosaur parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.proto.dino.Dinosaur parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.proto.dino.Dinosaur parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.proto.dino.Dinosaur parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.proto.dino.Dinosaur parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.proto.dino.Dinosaur parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.proto.dino.Dinosaur parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.proto.dino.Dinosaur parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.proto.dino.Dinosaur parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.proto.dino.Dinosaur prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code test3.Dinosaur}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.proto.dino.Dinosaur, Builder> implements
      // @@protoc_insertion_point(builder_implements:test3.Dinosaur)
      com.proto.dino.DinosaurOrBuilder {
    // Construct using com.proto.dino.Dinosaur.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Common name of this dinosaur, like "Stegosaurus".
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <pre>
     * Common name of this dinosaur, like "Stegosaurus".
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <pre>
     * Common name of this dinosaur, like "Stegosaurus".
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <pre>
     * Common name of this dinosaur, like "Stegosaurus".
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <pre>
     * Common name of this dinosaur, like "Stegosaurus".
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @return A list containing the pictureUrls.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getPictureUrlsList() {
      return java.util.Collections.unmodifiableList(
          instance.getPictureUrlsList());
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @return The count of pictureUrls.
     */
    @java.lang.Override
    public int getPictureUrlsCount() {
      return instance.getPictureUrlsCount();
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @param index The index of the element to return.
     * @return The pictureUrls at the given index.
     */
    @java.lang.Override
    public java.lang.String getPictureUrls(int index) {
      return instance.getPictureUrls(index);
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the pictureUrls at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPictureUrlsBytes(int index) {
      return instance.getPictureUrlsBytes(index);
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @param index The index to set the value at.
     * @param value The pictureUrls to set.
     * @return This builder for chaining.
     */
    public Builder setPictureUrls(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setPictureUrls(index, value);
      return this;
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @param value The pictureUrls to add.
     * @return This builder for chaining.
     */
    public Builder addPictureUrls(
        java.lang.String value) {
      copyOnWrite();
      instance.addPictureUrls(value);
      return this;
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @param values The pictureUrls to add.
     * @return This builder for chaining.
     */
    public Builder addAllPictureUrls(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllPictureUrls(values);
      return this;
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPictureUrls() {
      copyOnWrite();
      instance.clearPictureUrls();
      return this;
    }
    /**
     * <pre>
     * URLs with images of this dinosaur.
     * </pre>
     *
     * <code>repeated string picture_urls = 2;</code>
     * @param value The bytes of the pictureUrls to add.
     * @return This builder for chaining.
     */
    public Builder addPictureUrlsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addPictureUrlsBytes(value);
      return this;
    }

    /**
     * <code>.test3.Period period = 5;</code>
     * @return The enum numeric value on the wire for period.
     */
    @java.lang.Override
    public int getPeriodValue() {
      return instance.getPeriodValue();
    }
    /**
     * <code>.test3.Period period = 5;</code>
     * @param value The period to set.
     * @return This builder for chaining.
     */
    public Builder setPeriodValue(int value) {
      copyOnWrite();
      instance.setPeriodValue(value);
      return this;
    }
    /**
     * <code>.test3.Period period = 5;</code>
     * @return The period.
     */
    @java.lang.Override
    public com.proto.dino.Period getPeriod() {
      return instance.getPeriod();
    }
    /**
     * <code>.test3.Period period = 5;</code>
     * @param value The enum numeric value on the wire for period to set.
     * @return This builder for chaining.
     */
    public Builder setPeriod(com.proto.dino.Period value) {
      copyOnWrite();
      instance.setPeriod(value);
      return this;
    }
    /**
     * <code>.test3.Period period = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPeriod() {
      copyOnWrite();
      instance.clearPeriod();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:test3.Dinosaur)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.proto.dino.Dinosaur();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "name_",
            "pictureUrls_",
            "period_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0005\u0003\u0000\u0001\u0000\u0001\u0208\u0002\u021a" +
              "\u0005\f";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.proto.dino.Dinosaur> parser = PARSER;
        if (parser == null) {
          synchronized (com.proto.dino.Dinosaur.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.proto.dino.Dinosaur>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:test3.Dinosaur)
  private static final com.proto.dino.Dinosaur DEFAULT_INSTANCE;
  static {
    Dinosaur defaultInstance = new Dinosaur();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Dinosaur.class, defaultInstance);
  }

  public static com.proto.dino.Dinosaur getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Dinosaur> PARSER;

  public static com.google.protobuf.Parser<Dinosaur> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

