// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dino.proto

package com.proto.dino;

/**
 * Protobuf type {@code test3.FindDinoRequest}
 */
public  final class FindDinoRequest extends
    com.google.protobuf.GeneratedMessageLite<
        FindDinoRequest, FindDinoRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:test3.FindDinoRequest)
    FindDinoRequestOrBuilder {
  private FindDinoRequest() {
    searchString_ = "";
  }
  public static final int SEARCHSTRING_FIELD_NUMBER = 1;
  private java.lang.String searchString_;
  /**
   * <pre>
   * Search string
   * </pre>
   *
   * <code>string searchString = 1;</code>
   * @return The searchString.
   */
  @java.lang.Override
  public java.lang.String getSearchString() {
    return searchString_;
  }
  /**
   * <pre>
   * Search string
   * </pre>
   *
   * <code>string searchString = 1;</code>
   * @return The bytes for searchString.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSearchStringBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(searchString_);
  }
  /**
   * <pre>
   * Search string
   * </pre>
   *
   * <code>string searchString = 1;</code>
   * @param value The searchString to set.
   */
  private void setSearchString(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    searchString_ = value;
  }
  /**
   * <pre>
   * Search string
   * </pre>
   *
   * <code>string searchString = 1;</code>
   */
  private void clearSearchString() {
    
    searchString_ = getDefaultInstance().getSearchString();
  }
  /**
   * <pre>
   * Search string
   * </pre>
   *
   * <code>string searchString = 1;</code>
   * @param value The bytes for searchString to set.
   */
  private void setSearchStringBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    searchString_ = value.toStringUtf8();
    
  }

  public static com.proto.dino.FindDinoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.proto.dino.FindDinoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.proto.dino.FindDinoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.proto.dino.FindDinoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.proto.dino.FindDinoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.proto.dino.FindDinoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.proto.dino.FindDinoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.proto.dino.FindDinoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.proto.dino.FindDinoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.proto.dino.FindDinoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.proto.dino.FindDinoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.proto.dino.FindDinoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.proto.dino.FindDinoRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code test3.FindDinoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.proto.dino.FindDinoRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:test3.FindDinoRequest)
      com.proto.dino.FindDinoRequestOrBuilder {
    // Construct using com.proto.dino.FindDinoRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Search string
     * </pre>
     *
     * <code>string searchString = 1;</code>
     * @return The searchString.
     */
    @java.lang.Override
    public java.lang.String getSearchString() {
      return instance.getSearchString();
    }
    /**
     * <pre>
     * Search string
     * </pre>
     *
     * <code>string searchString = 1;</code>
     * @return The bytes for searchString.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSearchStringBytes() {
      return instance.getSearchStringBytes();
    }
    /**
     * <pre>
     * Search string
     * </pre>
     *
     * <code>string searchString = 1;</code>
     * @param value The searchString to set.
     * @return This builder for chaining.
     */
    public Builder setSearchString(
        java.lang.String value) {
      copyOnWrite();
      instance.setSearchString(value);
      return this;
    }
    /**
     * <pre>
     * Search string
     * </pre>
     *
     * <code>string searchString = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSearchString() {
      copyOnWrite();
      instance.clearSearchString();
      return this;
    }
    /**
     * <pre>
     * Search string
     * </pre>
     *
     * <code>string searchString = 1;</code>
     * @param value The bytes for searchString to set.
     * @return This builder for chaining.
     */
    public Builder setSearchStringBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSearchStringBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:test3.FindDinoRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.proto.dino.FindDinoRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "searchString_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.proto.dino.FindDinoRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.proto.dino.FindDinoRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.proto.dino.FindDinoRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:test3.FindDinoRequest)
  private static final com.proto.dino.FindDinoRequest DEFAULT_INSTANCE;
  static {
    FindDinoRequest defaultInstance = new FindDinoRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FindDinoRequest.class, defaultInstance);
  }

  public static com.proto.dino.FindDinoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FindDinoRequest> PARSER;

  public static com.google.protobuf.Parser<FindDinoRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

