// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dino.proto

package com.proto.dino;

/**
 * Protobuf enum {@code test3.Period}
 */
public enum Period
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 145.5 million years ago — 66.0 million years ago.
   * </pre>
   *
   * <code>CRETACEOUS = 0;</code>
   */
  CRETACEOUS(0),
  /**
   * <pre>
   * 201.3 million years ago — 145.0 million years ago.
   * </pre>
   *
   * <code>JURASSIC = 1;</code>
   */
  JURASSIC(1),
  /**
   * <pre>
   * 252.17 million years ago — 201.3 million years ago.
   * </pre>
   *
   * <code>TRIASSIC = 2;</code>
   */
  TRIASSIC(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 145.5 million years ago — 66.0 million years ago.
   * </pre>
   *
   * <code>CRETACEOUS = 0;</code>
   */
  public static final int CRETACEOUS_VALUE = 0;
  /**
   * <pre>
   * 201.3 million years ago — 145.0 million years ago.
   * </pre>
   *
   * <code>JURASSIC = 1;</code>
   */
  public static final int JURASSIC_VALUE = 1;
  /**
   * <pre>
   * 252.17 million years ago — 201.3 million years ago.
   * </pre>
   *
   * <code>TRIASSIC = 2;</code>
   */
  public static final int TRIASSIC_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Period valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Period forNumber(int value) {
    switch (value) {
      case 0: return CRETACEOUS;
      case 1: return JURASSIC;
      case 2: return TRIASSIC;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Period>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Period> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Period>() {
          public Period findValueByNumber(int number) {
            return Period.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.proto.dino.Dino.getDescriptor().getEnumTypes().get(0);
  }

  private static final Period[] VALUES = values();

  public static Period valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Period(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:test3.Period)
}

