// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dino.proto

package com.proto.dino;

/**
 * Protobuf enum {@code test3.Period}
 */
public enum Period
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <pre>
   * 145.5 million years ago — 66.0 million years ago.
   * </pre>
   *
   * <code>CRETACEOUS = 0;</code>
   */
  CRETACEOUS(0),
  /**
   * <pre>
   * 201.3 million years ago — 145.0 million years ago.
   * </pre>
   *
   * <code>JURASSIC = 1;</code>
   */
  JURASSIC(1),
  /**
   * <pre>
   * 252.17 million years ago — 201.3 million years ago.
   * </pre>
   *
   * <code>TRIASSIC = 2;</code>
   */
  TRIASSIC(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 145.5 million years ago — 66.0 million years ago.
   * </pre>
   *
   * <code>CRETACEOUS = 0;</code>
   */
  public static final int CRETACEOUS_VALUE = 0;
  /**
   * <pre>
   * 201.3 million years ago — 145.0 million years ago.
   * </pre>
   *
   * <code>JURASSIC = 1;</code>
   */
  public static final int JURASSIC_VALUE = 1;
  /**
   * <pre>
   * 252.17 million years ago — 201.3 million years ago.
   * </pre>
   *
   * <code>TRIASSIC = 2;</code>
   */
  public static final int TRIASSIC_VALUE = 2;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Period valueOf(int value) {
    return forNumber(value);
  }

  public static Period forNumber(int value) {
    switch (value) {
      case 0: return CRETACEOUS;
      case 1: return JURASSIC;
      case 2: return TRIASSIC;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Period>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Period> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Period>() {
          @java.lang.Override
          public Period findValueByNumber(int number) {
            return Period.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return PeriodVerifier.INSTANCE;
  }

  private static final class PeriodVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new PeriodVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return Period.forNumber(number) != null;
          }
        };

  private final int value;

  private Period(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:test3.Period)
}

