// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test3_nongrpc.proto

package com.proto.pure.test3;

public final class Test3Nongrpc {
  private Test3Nongrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
