// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test3.proto

package com.proto.test3;

public final class Test3 {
  private Test3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test3_TestService3Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test3_TestService3Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test3_TestService3Response_NestedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test3_TestService3Response_NestedMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test3_TestService3Response_MapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test3_TestService3Response_MapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test3_TestService3Response_MapFieldEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test3_TestService3Response_MapFieldEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test3_TestService3Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test3_TestService3Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test3_TestService3Request_NestedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test3_TestService3Request_NestedMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test3_TestService3Request_MapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test3_TestService3Request_MapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test3_TestService3Request_MapFieldEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test3_TestService3Request_MapFieldEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013test3.proto\022\005test3\032\031google/protobuf/an" +
      "y.proto\"\212\016\n\024TestService3Response\022\033\n\016opti" +
      "onalDouble\030\001 \001(\001H\001\210\001\001\022\026\n\016requiredDouble\030" +
      "\003 \001(\001\022\032\n\roptionalInt32\030\004 \001(\005H\002\210\001\001\022\025\n\rreq" +
      "uiredInt32\030\005 \001(\005\022\032\n\roptionalInt64\030\006 \001(\003H" +
      "\003\210\001\001\022\025\n\rrequiredInt64\030\007 \001(\003\022\033\n\016optionalU" +
      "int32\030\010 \001(\rH\004\210\001\001\022\026\n\016requiredUint32\030\014 \001(\r" +
      "\022\033\n\016optionalUint64\030\r \001(\004H\005\210\001\001\022\026\n\016require" +
      "dUint64\030\016 \001(\004\022\033\n\016optionalSint32\030\020 \001(\021H\006\210" +
      "\001\001\022\026\n\016requiredSint32\030\021 \001(\021\022\033\n\016optionalSi" +
      "nt64\030\022 \001(\022H\007\210\001\001\022\026\n\016requiredSint64\030\023 \001(\022\022" +
      "\034\n\017optionalFixed32\030\024 \001(\007H\010\210\001\001\022\027\n\017require" +
      "dFixed32\030\025 \001(\007\022\034\n\017optionalFixed64\030\026 \001(\006H" +
      "\t\210\001\001\022\027\n\017requiredFixed64\030\027 \001(\006\022\035\n\020optiona" +
      "lSfixed32\030\030 \001(\017H\n\210\001\001\022\030\n\020requiredSfixed32" +
      "\030\031 \001(\017\022\035\n\020optionalSfixed64\030\032 \001(\020H\013\210\001\001\022\030\n" +
      "\020requiredSfixed64\030\033 \001(\020\022\031\n\014optionalBool\030" +
      "\034 \001(\010H\014\210\001\001\022\024\n\014requiredBool\030\035 \001(\010\022\033\n\016opti" +
      "onalString\030\036 \001(\tH\r\210\001\001\022\026\n\016requiredString\030" +
      "\037 \001(\t\022\032\n\roptionalBytes\030  \001(\014H\016\210\001\001\022\025\n\rreq" +
      "uiredBytes\030! \001(\014\0227\n\006corpus\030$ \001(\0162\".test3" +
      ".TestService3Response.CorpusH\017\210\001\001\022\023\n\007sam" +
      "ples\030% \003(\005B\002\020\001\022\016\n\004name\030& \001(\tH\000\022;\n\006nested" +
      "\030\' \001(\0132).test3.TestService3Response.Nest" +
      "edMessageH\000\0221\n\003map\030( \003(\0132$.test3.TestSer" +
      "vice3Response.MapEntry\022<\n\tmap_field\030) \003(" +
      "\0132).test3.TestService3Response.MapFieldE" +
      "ntry\022%\n\007details\030* \003(\0132\024.google.protobuf." +
      "Any\032L\n\rNestedMessage\022\013\n\003url\030\001 \001(\t\022\022\n\005tit" +
      "le\030\002 \001(\tH\000\210\001\001\022\020\n\010snippets\030\003 \003(\tB\010\n\006_titl" +
      "e\032U\n\010MapEntry\022\013\n\003key\030\001 \001(\t\0228\n\005value\030\002 \001(" +
      "\0132).test3.TestService3Response.NestedMes" +
      "sage:\0028\001\032V\n\rMapFieldEntry\022\013\n\003key\030\001 \001(\t\0228" +
      "\n\005value\030\002 \001(\0132).test3.TestService3Respon" +
      "se.NestedMessage\"Z\n\006Corpus\022\r\n\tUNIVERSAL\020" +
      "\000\022\007\n\003WEB\020\001\022\n\n\006IMAGES\020\002\022\t\n\005LOCAL\020\003\022\010\n\004NEW" +
      "S\020\004\022\014\n\010PRODUCTS\020\005\022\t\n\005VIDEO\020\006\">\n\021EnumAllo" +
      "wingAlias\022\013\n\007UNKNOWN\020\000\022\013\n\007STARTED\020\001\022\013\n\007R" +
      "UNNING\020\001\032\002\020\001B\014\n\noneOfFieldB\021\n\017_optionalD" +
      "oubleB\020\n\016_optionalInt32B\020\n\016_optionalInt6" +
      "4B\021\n\017_optionalUint32B\021\n\017_optionalUint64B" +
      "\021\n\017_optionalSint32B\021\n\017_optionalSint64B\022\n" +
      "\020_optionalFixed32B\022\n\020_optionalFixed64B\023\n" +
      "\021_optionalSfixed32B\023\n\021_optionalSfixed64B" +
      "\017\n\r_optionalBoolB\021\n\017_optionalStringB\020\n\016_" +
      "optionalBytesB\t\n\007_corpusJ\004\010\002\020\003J\004\010\017\020\020J\004\010\t" +
      "\020\014R\003fooR\003bar\"\203\016\n\023TestService3Request\022\033\n\016" +
      "optionalDouble\030\001 \001(\001H\001\210\001\001\022\026\n\016requiredDou" +
      "ble\030\003 \001(\001\022\032\n\roptionalInt32\030\004 \001(\005H\002\210\001\001\022\025\n" +
      "\rrequiredInt32\030\005 \001(\005\022\032\n\roptionalInt64\030\006 " +
      "\001(\003H\003\210\001\001\022\025\n\rrequiredInt64\030\007 \001(\003\022\033\n\016optio" +
      "nalUint32\030\010 \001(\rH\004\210\001\001\022\026\n\016requiredUint32\030\014" +
      " \001(\r\022\033\n\016optionalUint64\030\r \001(\004H\005\210\001\001\022\026\n\016req" +
      "uiredUint64\030\016 \001(\004\022\033\n\016optionalSint32\030\020 \001(" +
      "\021H\006\210\001\001\022\026\n\016requiredSint32\030\021 \001(\021\022\033\n\016option" +
      "alSint64\030\022 \001(\022H\007\210\001\001\022\026\n\016requiredSint64\030\023 " +
      "\001(\022\022\034\n\017optionalFixed32\030\024 \001(\007H\010\210\001\001\022\027\n\017req" +
      "uiredFixed32\030\025 \001(\007\022\034\n\017optionalFixed64\030\026 " +
      "\001(\006H\t\210\001\001\022\027\n\017requiredFixed64\030\027 \001(\006\022\035\n\020opt" +
      "ionalSfixed32\030\030 \001(\017H\n\210\001\001\022\030\n\020requiredSfix" +
      "ed32\030\031 \001(\017\022\035\n\020optionalSfixed64\030\032 \001(\020H\013\210\001" +
      "\001\022\030\n\020requiredSfixed64\030\033 \001(\020\022\031\n\014optionalB" +
      "ool\030\034 \001(\010H\014\210\001\001\022\024\n\014requiredBool\030\035 \001(\010\022\033\n\016" +
      "optionalString\030\036 \001(\tH\r\210\001\001\022\026\n\016requiredStr" +
      "ing\030\037 \001(\t\022\032\n\roptionalBytes\030  \001(\014H\016\210\001\001\022\025\n" +
      "\rrequiredBytes\030! \001(\014\0226\n\006corpus\030$ \001(\0162!.t" +
      "est3.TestService3Request.CorpusH\017\210\001\001\022\023\n\007" +
      "samples\030% \003(\005B\002\020\001\022\016\n\004name\030& \001(\tH\000\022:\n\006nes" +
      "ted\030\' \001(\0132(.test3.TestService3Request.Ne" +
      "stedMessageH\000\0220\n\003map\030( \003(\0132#.test3.TestS" +
      "ervice3Request.MapEntry\022;\n\tmap_field\030) \003" +
      "(\0132(.test3.TestService3Request.MapFieldE" +
      "ntry\022%\n\007details\030* \003(\0132\024.google.protobuf." +
      "Any\032L\n\rNestedMessage\022\013\n\003url\030\001 \001(\t\022\022\n\005tit" +
      "le\030\002 \001(\tH\000\210\001\001\022\020\n\010snippets\030\003 \003(\tB\010\n\006_titl" +
      "e\032T\n\010MapEntry\022\013\n\003key\030\001 \001(\t\0227\n\005value\030\002 \001(" +
      "\0132(.test3.TestService3Request.NestedMess" +
      "age:\0028\001\032U\n\rMapFieldEntry\022\013\n\003key\030\001 \001(\t\0227\n" +
      "\005value\030\002 \001(\0132(.test3.TestService3Request" +
      ".NestedMessage\"Z\n\006Corpus\022\r\n\tUNIVERSAL\020\000\022" +
      "\007\n\003WEB\020\001\022\n\n\006IMAGES\020\002\022\t\n\005LOCAL\020\003\022\010\n\004NEWS\020" +
      "\004\022\014\n\010PRODUCTS\020\005\022\t\n\005VIDEO\020\006\">\n\021EnumAllowi" +
      "ngAlias\022\013\n\007UNKNOWN\020\000\022\013\n\007STARTED\020\001\022\013\n\007RUN" +
      "NING\020\001\032\002\020\001B\014\n\noneOfFieldB\021\n\017_optionalDou" +
      "bleB\020\n\016_optionalInt32B\020\n\016_optionalInt64B" +
      "\021\n\017_optionalUint32B\021\n\017_optionalUint64B\021\n" +
      "\017_optionalSint32B\021\n\017_optionalSint64B\022\n\020_" +
      "optionalFixed32B\022\n\020_optionalFixed64B\023\n\021_" +
      "optionalSfixed32B\023\n\021_optionalSfixed64B\017\n" +
      "\r_optionalBoolB\021\n\017_optionalStringB\020\n\016_op" +
      "tionalBytesB\t\n\007_corpusJ\004\010\002\020\003J\004\010\017\020\020J\004\010\t\020\014" +
      "R\003fooR\003bar2Q\n\014TestService3\022A\n\004test\022\032.tes" +
      "t3.TestService3Request\032\033.test3.TestServi" +
      "ce3Response\"\000B\023\n\017com.proto.test3P\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_test3_TestService3Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test3_TestService3Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test3_TestService3Response_descriptor,
        new java.lang.String[] { "OptionalDouble", "RequiredDouble", "OptionalInt32", "RequiredInt32", "OptionalInt64", "RequiredInt64", "OptionalUint32", "RequiredUint32", "OptionalUint64", "RequiredUint64", "OptionalSint32", "RequiredSint32", "OptionalSint64", "RequiredSint64", "OptionalFixed32", "RequiredFixed32", "OptionalFixed64", "RequiredFixed64", "OptionalSfixed32", "RequiredSfixed32", "OptionalSfixed64", "RequiredSfixed64", "OptionalBool", "RequiredBool", "OptionalString", "RequiredString", "OptionalBytes", "RequiredBytes", "Corpus", "Samples", "Name", "Nested", "Map", "MapField", "Details", "OneOfField", "OptionalDouble", "OptionalInt32", "OptionalInt64", "OptionalUint32", "OptionalUint64", "OptionalSint32", "OptionalSint64", "OptionalFixed32", "OptionalFixed64", "OptionalSfixed32", "OptionalSfixed64", "OptionalBool", "OptionalString", "OptionalBytes", "Corpus", });
    internal_static_test3_TestService3Response_NestedMessage_descriptor =
      internal_static_test3_TestService3Response_descriptor.getNestedTypes().get(0);
    internal_static_test3_TestService3Response_NestedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test3_TestService3Response_NestedMessage_descriptor,
        new java.lang.String[] { "Url", "Title", "Snippets", "Title", });
    internal_static_test3_TestService3Response_MapEntry_descriptor =
      internal_static_test3_TestService3Response_descriptor.getNestedTypes().get(1);
    internal_static_test3_TestService3Response_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test3_TestService3Response_MapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_test3_TestService3Response_MapFieldEntry_descriptor =
      internal_static_test3_TestService3Response_descriptor.getNestedTypes().get(2);
    internal_static_test3_TestService3Response_MapFieldEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test3_TestService3Response_MapFieldEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_test3_TestService3Request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_test3_TestService3Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test3_TestService3Request_descriptor,
        new java.lang.String[] { "OptionalDouble", "RequiredDouble", "OptionalInt32", "RequiredInt32", "OptionalInt64", "RequiredInt64", "OptionalUint32", "RequiredUint32", "OptionalUint64", "RequiredUint64", "OptionalSint32", "RequiredSint32", "OptionalSint64", "RequiredSint64", "OptionalFixed32", "RequiredFixed32", "OptionalFixed64", "RequiredFixed64", "OptionalSfixed32", "RequiredSfixed32", "OptionalSfixed64", "RequiredSfixed64", "OptionalBool", "RequiredBool", "OptionalString", "RequiredString", "OptionalBytes", "RequiredBytes", "Corpus", "Samples", "Name", "Nested", "Map", "MapField", "Details", "OneOfField", "OptionalDouble", "OptionalInt32", "OptionalInt64", "OptionalUint32", "OptionalUint64", "OptionalSint32", "OptionalSint64", "OptionalFixed32", "OptionalFixed64", "OptionalSfixed32", "OptionalSfixed64", "OptionalBool", "OptionalString", "OptionalBytes", "Corpus", });
    internal_static_test3_TestService3Request_NestedMessage_descriptor =
      internal_static_test3_TestService3Request_descriptor.getNestedTypes().get(0);
    internal_static_test3_TestService3Request_NestedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test3_TestService3Request_NestedMessage_descriptor,
        new java.lang.String[] { "Url", "Title", "Snippets", "Title", });
    internal_static_test3_TestService3Request_MapEntry_descriptor =
      internal_static_test3_TestService3Request_descriptor.getNestedTypes().get(1);
    internal_static_test3_TestService3Request_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test3_TestService3Request_MapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_test3_TestService3Request_MapFieldEntry_descriptor =
      internal_static_test3_TestService3Request_descriptor.getNestedTypes().get(2);
    internal_static_test3_TestService3Request_MapFieldEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test3_TestService3Request_MapFieldEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
