// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test2.proto

package com.proto.test2;

public final class Test2 {
  private Test2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.proto.test2.Test2.extension);
    registry.add(com.proto.test2.Test2.extensionScope);
  }
  public static final int EXTENSION_FIELD_NUMBER = 126;
  /**
   * <code>extend .test2.TestService2Response { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.proto.test2.TestService2Response,
      java.lang.Integer> extension = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.proto.test2.TestService2Response.getDefaultInstance(),
        0,
        null,
        null,
        126,
        com.google.protobuf.WireFormat.FieldType.INT32,
        java.lang.Integer.class);
  public static final int EXTENSION_SCOPE_FIELD_NUMBER = 126;
  /**
   * <code>extend .test2.TestService2Request { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.proto.test2.TestService2Request,
      java.lang.Integer> extensionScope = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.proto.test2.TestService2Request.getDefaultInstance(),
        0,
        null,
        null,
        126,
        com.google.protobuf.WireFormat.FieldType.INT32,
        java.lang.Integer.class);

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
