// Code generated by Wire protocol buffer compiler, do not edit.
// Source: test2.TestService2 in test2.proto
package com.proto.test2

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod

public class GrpcTestService2Client(
  private val client: GrpcClient
) : TestService2Client {
  /**
   * Unary
   */
  public override fun test(): GrpcCall<TestService2Request, TestService2Response> =
      client.newCall(GrpcMethod(
      path = "/test2.TestService2/test",
      requestAdapter = TestService2Request.ADAPTER,
      responseAdapter = TestService2Response.ADAPTER
  ))
}
