// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test2.proto

package com.proto.test2;

public interface TestService2RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test2.TestService2Request)
    com.google.protobuf.GeneratedMessageV3.
        ExtendableMessageOrBuilder<TestService2Request> {

  /**
   * <pre>
   *  https://developers.google.com/protocol-buffers/docs/proto#specifying-rules
   *  https://developers.google.com/protocol-buffers/docs/proto#scalar
   * </pre>
   *
   * <code>optional double optionalDouble = 1;</code>
   * @return Whether the optionalDouble field is set.
   */
  boolean hasOptionalDouble();
  /**
   * <pre>
   *  https://developers.google.com/protocol-buffers/docs/proto#specifying-rules
   *  https://developers.google.com/protocol-buffers/docs/proto#scalar
   * </pre>
   *
   * <code>optional double optionalDouble = 1;</code>
   * @return The optionalDouble.
   */
  double getOptionalDouble();

  /**
   * <code>required double requiredDouble = 3;</code>
   * @return Whether the requiredDouble field is set.
   */
  boolean hasRequiredDouble();
  /**
   * <code>required double requiredDouble = 3;</code>
   * @return The requiredDouble.
   */
  double getRequiredDouble();

  /**
   * <code>optional int32 optionalInt32 = 4;</code>
   * @return Whether the optionalInt32 field is set.
   */
  boolean hasOptionalInt32();
  /**
   * <code>optional int32 optionalInt32 = 4;</code>
   * @return The optionalInt32.
   */
  int getOptionalInt32();

  /**
   * <code>required int32 requiredInt32 = 5;</code>
   * @return Whether the requiredInt32 field is set.
   */
  boolean hasRequiredInt32();
  /**
   * <code>required int32 requiredInt32 = 5;</code>
   * @return The requiredInt32.
   */
  int getRequiredInt32();

  /**
   * <code>optional int64 optionalInt64 = 6;</code>
   * @return Whether the optionalInt64 field is set.
   */
  boolean hasOptionalInt64();
  /**
   * <code>optional int64 optionalInt64 = 6;</code>
   * @return The optionalInt64.
   */
  long getOptionalInt64();

  /**
   * <code>required int64 requiredInt64 = 7;</code>
   * @return Whether the requiredInt64 field is set.
   */
  boolean hasRequiredInt64();
  /**
   * <code>required int64 requiredInt64 = 7;</code>
   * @return The requiredInt64.
   */
  long getRequiredInt64();

  /**
   * <code>optional uint32 optionalUint32 = 8;</code>
   * @return Whether the optionalUint32 field is set.
   */
  boolean hasOptionalUint32();
  /**
   * <code>optional uint32 optionalUint32 = 8;</code>
   * @return The optionalUint32.
   */
  int getOptionalUint32();

  /**
   * <code>required uint32 requiredUint32 = 12;</code>
   * @return Whether the requiredUint32 field is set.
   */
  boolean hasRequiredUint32();
  /**
   * <code>required uint32 requiredUint32 = 12;</code>
   * @return The requiredUint32.
   */
  int getRequiredUint32();

  /**
   * <code>optional uint64 optionalUint64 = 13;</code>
   * @return Whether the optionalUint64 field is set.
   */
  boolean hasOptionalUint64();
  /**
   * <code>optional uint64 optionalUint64 = 13;</code>
   * @return The optionalUint64.
   */
  long getOptionalUint64();

  /**
   * <code>required uint64 requiredUint64 = 14;</code>
   * @return Whether the requiredUint64 field is set.
   */
  boolean hasRequiredUint64();
  /**
   * <code>required uint64 requiredUint64 = 14;</code>
   * @return The requiredUint64.
   */
  long getRequiredUint64();

  /**
   * <code>optional sint32 optionalSint32 = 16;</code>
   * @return Whether the optionalSint32 field is set.
   */
  boolean hasOptionalSint32();
  /**
   * <code>optional sint32 optionalSint32 = 16;</code>
   * @return The optionalSint32.
   */
  int getOptionalSint32();

  /**
   * <code>required sint32 requiredSint32 = 17;</code>
   * @return Whether the requiredSint32 field is set.
   */
  boolean hasRequiredSint32();
  /**
   * <code>required sint32 requiredSint32 = 17;</code>
   * @return The requiredSint32.
   */
  int getRequiredSint32();

  /**
   * <code>optional sint64 optionalSint64 = 18;</code>
   * @return Whether the optionalSint64 field is set.
   */
  boolean hasOptionalSint64();
  /**
   * <code>optional sint64 optionalSint64 = 18;</code>
   * @return The optionalSint64.
   */
  long getOptionalSint64();

  /**
   * <code>required sint64 requiredSint64 = 19;</code>
   * @return Whether the requiredSint64 field is set.
   */
  boolean hasRequiredSint64();
  /**
   * <code>required sint64 requiredSint64 = 19;</code>
   * @return The requiredSint64.
   */
  long getRequiredSint64();

  /**
   * <code>optional fixed32 optionalFixed32 = 20;</code>
   * @return Whether the optionalFixed32 field is set.
   */
  boolean hasOptionalFixed32();
  /**
   * <code>optional fixed32 optionalFixed32 = 20;</code>
   * @return The optionalFixed32.
   */
  int getOptionalFixed32();

  /**
   * <code>required fixed32 requiredFixed32 = 21;</code>
   * @return Whether the requiredFixed32 field is set.
   */
  boolean hasRequiredFixed32();
  /**
   * <code>required fixed32 requiredFixed32 = 21;</code>
   * @return The requiredFixed32.
   */
  int getRequiredFixed32();

  /**
   * <code>optional fixed64 optionalFixed64 = 22;</code>
   * @return Whether the optionalFixed64 field is set.
   */
  boolean hasOptionalFixed64();
  /**
   * <code>optional fixed64 optionalFixed64 = 22;</code>
   * @return The optionalFixed64.
   */
  long getOptionalFixed64();

  /**
   * <code>required fixed64 requiredFixed64 = 23;</code>
   * @return Whether the requiredFixed64 field is set.
   */
  boolean hasRequiredFixed64();
  /**
   * <code>required fixed64 requiredFixed64 = 23;</code>
   * @return The requiredFixed64.
   */
  long getRequiredFixed64();

  /**
   * <code>optional sfixed32 optionalSfixed32 = 24;</code>
   * @return Whether the optionalSfixed32 field is set.
   */
  boolean hasOptionalSfixed32();
  /**
   * <code>optional sfixed32 optionalSfixed32 = 24;</code>
   * @return The optionalSfixed32.
   */
  int getOptionalSfixed32();

  /**
   * <code>required sfixed32 requiredSfixed32 = 25;</code>
   * @return Whether the requiredSfixed32 field is set.
   */
  boolean hasRequiredSfixed32();
  /**
   * <code>required sfixed32 requiredSfixed32 = 25;</code>
   * @return The requiredSfixed32.
   */
  int getRequiredSfixed32();

  /**
   * <code>optional sfixed64 optionalSfixed64 = 26;</code>
   * @return Whether the optionalSfixed64 field is set.
   */
  boolean hasOptionalSfixed64();
  /**
   * <code>optional sfixed64 optionalSfixed64 = 26;</code>
   * @return The optionalSfixed64.
   */
  long getOptionalSfixed64();

  /**
   * <code>required sfixed64 requiredSfixed64 = 27;</code>
   * @return Whether the requiredSfixed64 field is set.
   */
  boolean hasRequiredSfixed64();
  /**
   * <code>required sfixed64 requiredSfixed64 = 27;</code>
   * @return The requiredSfixed64.
   */
  long getRequiredSfixed64();

  /**
   * <code>optional bool optionalBool = 28;</code>
   * @return Whether the optionalBool field is set.
   */
  boolean hasOptionalBool();
  /**
   * <code>optional bool optionalBool = 28;</code>
   * @return The optionalBool.
   */
  boolean getOptionalBool();

  /**
   * <code>required bool requiredBool = 29;</code>
   * @return Whether the requiredBool field is set.
   */
  boolean hasRequiredBool();
  /**
   * <code>required bool requiredBool = 29;</code>
   * @return The requiredBool.
   */
  boolean getRequiredBool();

  /**
   * <code>optional string optionalString = 30;</code>
   * @return Whether the optionalString field is set.
   */
  boolean hasOptionalString();
  /**
   * <code>optional string optionalString = 30;</code>
   * @return The optionalString.
   */
  java.lang.String getOptionalString();
  /**
   * <code>optional string optionalString = 30;</code>
   * @return The bytes for optionalString.
   */
  com.google.protobuf.ByteString
      getOptionalStringBytes();

  /**
   * <code>required string requiredString = 31;</code>
   * @return Whether the requiredString field is set.
   */
  boolean hasRequiredString();
  /**
   * <code>required string requiredString = 31;</code>
   * @return The requiredString.
   */
  java.lang.String getRequiredString();
  /**
   * <code>required string requiredString = 31;</code>
   * @return The bytes for requiredString.
   */
  com.google.protobuf.ByteString
      getRequiredStringBytes();

  /**
   * <code>optional bytes optionalBytes = 32;</code>
   * @return Whether the optionalBytes field is set.
   */
  boolean hasOptionalBytes();
  /**
   * <code>optional bytes optionalBytes = 32;</code>
   * @return The optionalBytes.
   */
  com.google.protobuf.ByteString getOptionalBytes();

  /**
   * <code>required bytes requiredBytes = 33;</code>
   * @return Whether the requiredBytes field is set.
   */
  boolean hasRequiredBytes();
  /**
   * <code>required bytes requiredBytes = 33;</code>
   * @return The requiredBytes.
   */
  com.google.protobuf.ByteString getRequiredBytes();

  /**
   * <code>optional int32 optionalWithDefaultInt32 = 34 [default = 10];</code>
   * @return Whether the optionalWithDefaultInt32 field is set.
   */
  boolean hasOptionalWithDefaultInt32();
  /**
   * <code>optional int32 optionalWithDefaultInt32 = 34 [default = 10];</code>
   * @return The optionalWithDefaultInt32.
   */
  int getOptionalWithDefaultInt32();

  /**
   * <code>optional string optionalWithDefaultString = 35 [default = "temp_holder"];</code>
   * @return Whether the optionalWithDefaultString field is set.
   */
  boolean hasOptionalWithDefaultString();
  /**
   * <code>optional string optionalWithDefaultString = 35 [default = "temp_holder"];</code>
   * @return The optionalWithDefaultString.
   */
  java.lang.String getOptionalWithDefaultString();
  /**
   * <code>optional string optionalWithDefaultString = 35 [default = "temp_holder"];</code>
   * @return The bytes for optionalWithDefaultString.
   */
  com.google.protobuf.ByteString
      getOptionalWithDefaultStringBytes();

  /**
   * <code>optional .test2.TestService2Request.Corpus corpus = 36 [default = UNIVERSAL];</code>
   * @return Whether the corpus field is set.
   */
  boolean hasCorpus();
  /**
   * <code>optional .test2.TestService2Request.Corpus corpus = 36 [default = UNIVERSAL];</code>
   * @return The corpus.
   */
  com.proto.test2.TestService2Request.Corpus getCorpus();

  /**
   * <pre>
   *  https://developers.google.com/protocol-buffers/docs/proto#other
   * </pre>
   *
   * <code>repeated int32 samples = 37 [packed = true];</code>
   * @return A list containing the samples.
   */
  java.util.List<java.lang.Integer> getSamplesList();
  /**
   * <pre>
   *  https://developers.google.com/protocol-buffers/docs/proto#other
   * </pre>
   *
   * <code>repeated int32 samples = 37 [packed = true];</code>
   * @return The count of samples.
   */
  int getSamplesCount();
  /**
   * <pre>
   *  https://developers.google.com/protocol-buffers/docs/proto#other
   * </pre>
   *
   * <code>repeated int32 samples = 37 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The samples at the given index.
   */
  int getSamples(int index);

  /**
   * <code>string name = 38;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>string name = 38;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 38;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.test2.TestService2Request.NestedMessage nested = 39;</code>
   * @return Whether the nested field is set.
   */
  boolean hasNested();
  /**
   * <code>.test2.TestService2Request.NestedMessage nested = 39;</code>
   * @return The nested.
   */
  com.proto.test2.TestService2Request.NestedMessage getNested();
  /**
   * <code>.test2.TestService2Request.NestedMessage nested = 39;</code>
   */
  com.proto.test2.TestService2Request.NestedMessageOrBuilder getNestedOrBuilder();

  /**
   * <pre>
   *  https://developers.google.com/protocol-buffers/docs/proto#maps (MAps can't have lables)
   * </pre>
   *
   * <code>map&lt;string, .test2.TestService2Request.NestedMessage&gt; map = 40;</code>
   */
  int getMapCount();
  /**
   * <pre>
   *  https://developers.google.com/protocol-buffers/docs/proto#maps (MAps can't have lables)
   * </pre>
   *
   * <code>map&lt;string, .test2.TestService2Request.NestedMessage&gt; map = 40;</code>
   */
  boolean containsMap(
      java.lang.String key);
  /**
   * Use {@link #getMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.proto.test2.TestService2Request.NestedMessage>
  getMap();
  /**
   * <pre>
   *  https://developers.google.com/protocol-buffers/docs/proto#maps (MAps can't have lables)
   * </pre>
   *
   * <code>map&lt;string, .test2.TestService2Request.NestedMessage&gt; map = 40;</code>
   */
  java.util.Map<java.lang.String, com.proto.test2.TestService2Request.NestedMessage>
  getMapMap();
  /**
   * <pre>
   *  https://developers.google.com/protocol-buffers/docs/proto#maps (MAps can't have lables)
   * </pre>
   *
   * <code>map&lt;string, .test2.TestService2Request.NestedMessage&gt; map = 40;</code>
   */

  /* nullable */
com.proto.test2.TestService2Request.NestedMessage getMapOrDefault(
      java.lang.String key,
      /* nullable */
com.proto.test2.TestService2Request.NestedMessage defaultValue);
  /**
   * <pre>
   *  https://developers.google.com/protocol-buffers/docs/proto#maps (MAps can't have lables)
   * </pre>
   *
   * <code>map&lt;string, .test2.TestService2Request.NestedMessage&gt; map = 40;</code>
   */

  com.proto.test2.TestService2Request.NestedMessage getMapOrThrow(
      java.lang.String key);

  /**
   * <code>repeated .test2.TestService2Request.MapFieldEntry map_field = 41;</code>
   */
  java.util.List<com.proto.test2.TestService2Request.MapFieldEntry> 
      getMapFieldList();
  /**
   * <code>repeated .test2.TestService2Request.MapFieldEntry map_field = 41;</code>
   */
  com.proto.test2.TestService2Request.MapFieldEntry getMapField(int index);
  /**
   * <code>repeated .test2.TestService2Request.MapFieldEntry map_field = 41;</code>
   */
  int getMapFieldCount();
  /**
   * <code>repeated .test2.TestService2Request.MapFieldEntry map_field = 41;</code>
   */
  java.util.List<? extends com.proto.test2.TestService2Request.MapFieldEntryOrBuilder> 
      getMapFieldOrBuilderList();
  /**
   * <code>repeated .test2.TestService2Request.MapFieldEntry map_field = 41;</code>
   */
  com.proto.test2.TestService2Request.MapFieldEntryOrBuilder getMapFieldOrBuilder(
      int index);

  /**
   * <code>required .test2.TestService2Request.NestedMessage requiredMessageObject = 42;</code>
   * @return Whether the requiredMessageObject field is set.
   */
  boolean hasRequiredMessageObject();
  /**
   * <code>required .test2.TestService2Request.NestedMessage requiredMessageObject = 42;</code>
   * @return The requiredMessageObject.
   */
  com.proto.test2.TestService2Request.NestedMessage getRequiredMessageObject();
  /**
   * <code>required .test2.TestService2Request.NestedMessage requiredMessageObject = 42;</code>
   */
  com.proto.test2.TestService2Request.NestedMessageOrBuilder getRequiredMessageObjectOrBuilder();

  public com.proto.test2.TestService2Request.OneOfFieldCase getOneOfFieldCase();
}
