// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test3.proto

package com.proto.test3;

public final class Test3 {
  private Test3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
